### PR TITLE
Add `Ingress` resource for root of the prometheus domain

### PR DESCRIPTION
**Pull request by mig4**
It is added here as Promxy will be replacing the Prometheus backend
served under `/` of the domain eventually and so this will replace the
resource currently defined in `ingress.yaml`.

Towards: https://github.com/giantswarm/giantswarm/issues/14951

### CODE REVIEW

**Comment by mig4** [comment]
Diff with _g8s-prometheus_:

``` diff
--- ../g8s-prometheus/helm/g8s-prometheus/templates/prometheus/ingress.yaml     2020-10-29 17:20:46.776151305 +0000
+++ helm/promxy-app/templates/ingress-root.yaml 2021-01-28 12:37:19.030422733 +0000
@@ -1,10 +1,11 @@
+# TODO: replace `ingress.yaml` with this when removing Prometheus from g8s-prometheus
 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
-  name: {{ .Values.resource.prometheus.name }}
-  namespace: {{ .Values.resource.default.namespace }}
+  name: {{ include "resource.prometheus.serviceName" . }}
+  namespace: {{ include "resource.default.namespace" . }}
   labels:
-    app: {{ .Values.resource.prometheus.name }}
+    app: {{ include "resource.prometheus.serviceName" . }}
   annotations:
     kubernetes.io/ingress.class: "nginx"
     {{- if .Values.Installation.V1.Monitoring.Prometheus.Letsencrypt }}
@@ -30,5 +31,5 @@
       paths:
       - path: /
         backend:
-          serviceName: {{ .Values.resource.prometheus.name }}
-          servicePort: {{ .Values.ports.prometheus.port }}
+          serviceName: {{ include "resource.prometheus.serviceName" . }}
+          servicePort: {{ include "resource.prometheus.servicePort" . }}
```

**Comment by mig4** [comment]
Also wondering about adding the ingress for OAuth proxy here, thoughts?

**Comment by QuentinBisson** [comment]
Adding the 2 ingresses here would make sense. I would just upgrade the ingress to the v1 version though

**Comment by QuentinBisson** [comment]
Also, I am not sure why you can't remove the ingress from g8s-prometheus, release it and then release the ingress in pmo

**Comment by mig4** [comment]
> Also, I am not sure why you can't remove the ingress from g8s-prometheus, release it and then release the ingress in pmo

Yeah, PR for removal from _g8s-prometheus_ incoming, then it will be a matter of timing releases right. Or did you mean something else?

As for why not in PMO, it just doesn't seem to belong there, as the resource will be pointing to the Promxy service, not to anything created by PMO. Also that would create a sort of weird circular dependency between Promxy and PMO.

Good shout about the version, I was wondering when I copied it but left it for now to check if there are any changes (I seem to remember there was something, but maybe I'm thinking of Ingress v2).

**Comment by QuentinBisson** [comment]
Coordinating releases is what I meant :) I will get a lot of heartbeats but hey :D

I think we kinda have a chicken egg situation here as the individual prometheus are gonna be dependent on the ingress and cert being there to have a certificate generated

**Comment by mig4** [comment]
> I think we kinda have a chicken egg situation here as the individual prometheus are gonna be dependent on the ingress and cert being there to have a certificate generated

Yeah, they already do, and for a minute there I was wondering if this should actually be a separate component, like a `prometheus-ingress` chart that just installs the `/` ingress and OAuth proxy one. Seems like a bit of an overhead but the upside is the dependency graph would be nicer.

**Comment by QuentinBisson** [comment]
Yes, let's discuss it during standup tomorrow :D

**Comment by mig4** [comment]
Hey @QuentinBisson, regarding updating to `Ingress` `networking.k8s.io/v1`, it seems I remembered right, it was introduced in k8s 1.19 and there are some changes like new `spec.ingressClassName` field to use instead of the `kubernetes.io/ingress.class` annotation, a `pathType` setting for each path, etc. Are you sure we're ready for this? Do we use this version anywhere else already?

**Comment by QuentinBisson** [comment]
In that case, let's keep the beta version for now :D

**Comment by TheoBrigitte** [comment]
What do we do with this ?

**Comment by QuentinBisson** [comment]
We need to finish it up to close our epic

**Review by TheoBrigitte — APPROVED** [review]

**Review by QuentinBisson — APPROVED** [review]

**Pull request merged**
